CREATE TABLE USUARIO(
	Id_Usuario INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Usuario VARCHAR(50) NOT NULL,
	Tipo_Usr VARCHAR(50) NOT NULL,
	Nacimiento DATE NOT NULL,
	Pass VARCHAR(50)NOT NULL
);


CREATE TABLE BITACORA(
	Id_bitacora INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Fecha Date NOT NULL,
	Usuario VARCHAR(50) NOT NULL,
	IpU VARCHAR(50) NOT NULL,
	Accion VARCHAR(50)NOT NULL
);

CREATE TABLE PRESTAMO(
	Id_prestamo INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_USUARIO INT NOT NULL, 
	ID_LIBRO INT NOT NULL, 
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (Id_Usuario),
	FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID_LIBRO)
	
);

CREATE TABLE LIBRO(
	ID_LIBRO INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_EDITORIAL INT NOT NULL, 
	GENERO INT NOT NULL, 
	TITULO VARCHAR(50) NOT NULL, 
	AUTOR VARCHAR(50) NOT NULL, 
	CANTIDAD INT NOT NULL,
	FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL (Id_EDITORIAL),
	FOREIGN KEY (GENERO) REFERENCES GENERO (ID_GENERO)
	
);

CREATE TABLE GENERO(
	ID_GENERO INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
);

INSERT INTO GENERO (NOMBRE) VALUES ('SUSPENSO');

CREATE TABLE EDITORIAL(
	ID_EDITORIAL INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	TELEFONO INT NOT NULL
);

SELECT * FROM USUARIO
SELECT * FROM PRESTAMO
SELECT * FROM EDITORIAL
SELECT * FROM GENERO
SELECT * FROM LIBRO
SELECT * FROM BITACORA